services:
  service-dispatcher:
    # For dev we keep the golang container and install devtools
    build:
      target: plugin-debug
    image: codeclarityce/service-dispatcher-debug:latest
    ports:
      - 40000:40000
